# Generated by Django 5.1.5 on 2025-01-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
    ]
