name: Deploy Django App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

#    - name: Install sshpass
#      run: sudo apt install -y sshpass

    - name: Deploy to server
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        python -m venv .venv2
        source .venv2/bin/activate
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver



#        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
#        cd /path/to/your/project
#        git pull origin main
#        source /path/to/venv/bin/activate
#        pip install -r requirements.txt
#        python manage.py migrate
#        EOF
